version: "3.3"
services:
  currency_app:
    container_name: currency_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - currency_db
    networks:
      - app_network

  currency_nginx:
    container_name: currency_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - "8000:80"
    depends_on:
      - currency_app
    environment:
      NGINX_FPM_HOST: currency_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  currency_db:
    container_name: currency_db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: currency
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
